development:
  adapter: postgresql
  encoding: unicode
  database: cards_development
  min_messages: WARNING
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: cards_test
  min_messages: WARNING
  pool: 5
