# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea0ce61825ec297677a83d28eba43062f1e514736392943357c03cc07d371d8fd4c03615a7b1d36936c757c5db44d9121d3a75fcd588d2a12319abd6239fc73a

test:
  secret_key_base: d2e3a41d86081bd16e3a12d907a114db0502003b2c5c8de0b955585d70e9fc3f5b827e23c2693d38a9e0bcbde7aa53b16a2deccc8202f23f9a26ed16bcc5ac0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
